# Generated by Django 6.0.3 on 2026-05-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cartitem_price_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='original_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.appointment'),
        ),
    ]
