# Generated by Django 6.0.3 on 2026-04-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_icubooking_contact_number_icubooking_patient_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('x_ray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('urine_test', 'Urine Test'), ('stool_test', 'Stool Test'), ('ecg', 'ECG'), ('other', 'Other')], default='other', max_length=20)),
                ('report_title', models.CharField(blank=True, max_length=200)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('normal_range', models.TextField(blank=True)),
                ('test_results', models.TextField(blank=True)),
                ('interpretation', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='test_reports/images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_reports', to='myapp.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='myapp.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='myapp.patient')),
            ],
            options={
                'verbose_name': 'Test Report',
                'verbose_name_plural': 'Test Reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
