# Generated by Django 6.0.5 on 2026-05-20 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointment_original_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relations', to='myapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relations', to='myapp.patient')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='myapp.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Patient Relation',
                'verbose_name_plural': 'Doctor Patient Relations',
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
