# Generated by Django 6.0.5 on 2026-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doctorpatientrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_advice',
            field=models.TextField(blank=True, help_text='Advice given to patient', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text='Clinical notes from doctor', null=True),
        ),
    ]
