# Generated by Django 6.0.3 on 2026-04-23 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_patient_hospital_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('free_delivery_above', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pharmacyorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='pharmacyadmin',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='pharmacyorder',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='pharmacyorder',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pharmacyproduct',
            name='hospital',
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum Retail Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('mobile', 'Mobile Banking (bKash/Nagad)')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pharmacyproduct',
            name='category',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('equipment', 'Medical Equipment'), ('supplement', 'Health Supplement'), ('personal_care', 'Personal Care'), ('baby_care', 'Baby Care'), ('ayurvedic', 'Ayurvedic'), ('homeopathy', 'Homeopathy'), ('other', 'Other')], default='medicine', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('pharmacy_admin', 'Pharmacy Admin'), ('pharmacy_customer', 'Pharmacy Customer')], default='patient', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacyadmin',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='myapp.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.pharmacy'),
        ),
        migrations.CreateModel(
            name='PharmacyCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.pharmacycart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacycart',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='myapp.pharmacycustomer'),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.pharmacycustomer'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='prescriptions/')),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('doctor_registration', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='myapp.pharmacycustomer')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='myapp.pharmacy')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pharmacyadmin')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myapp.prescription'),
        ),
    ]
