# Generated by Django 6.0.3 on 2026-04-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pharmacy_pharmacycart_alter_pharmacyorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyproduct',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.pharmacy'),
        ),
    ]
