# Generated by Django 6.0.3 on 2026-04-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pharmacyproduct_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='default_consultation_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='default_end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='default_max_patients',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='default_start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('max_patients', models.IntegerField(default=20)),
                ('consultation_duration', models.IntegerField(default=30, help_text='Minutes per patient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='myapp.doctor')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('doctor', 'day')},
            },
        ),
    ]
