# Generated by Django 6.0.3 on 2026-04-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_doctor_default_consultation_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['name'], 'verbose_name': 'Pharmacy', 'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.AlterModelOptions(
            name='pharmacyadmin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pharmacy Admin', 'verbose_name_plural': 'Pharmacy Admins'},
        ),
        migrations.AddField(
            model_name='pharmacyadmin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
