# Generated by Django 6.0.3 on 2026-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_pharmacy_options_alter_pharmacyadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pharmacyadmin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testreport',
            options={'ordering': ['-report_date']},
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='consultation_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('mobile', 'Mobile Banking')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyproduct',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
